Update the local e2e ilab guide
instructlab/docs.instructlab.ai pull request #15
Opened 2024-11-12 15:11 UTC by kelbrown20

**Description:** Update the "Adding data to model" section that goes through the local instructlab process so its up to date with the current README

2024-11-21 15:13 UTC, jjasghar requested changes
the `--simple` flag is going away? I think it is.

2024-12-05 17:58 UTC, kelbrown20 commented on docs/adding-data-to-model/creating_new_knowledge_or_skills.md
>     ilab data generate --pipeline simple
I think it was on the roadmap, but not happening at least for a little bit 
@cdoern

2024-12-12 00:53 UTC, cdoern approved these changes
simple is going away, but not for a few releases. So documenting it makes sense. Especially since the releases with it will be out in the wild for a while.

2024-12-12 15:08 UTC, jjasghar approved these changes

2024-12-12 15:08 UTC, merged